import os
import pickle
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

from dd_hdg_training8 import DD_HDG_Trainer
from dd_hdg_face_operations import extract_neighbours_indexes
from dd_hdg_SVD import reconstruct_from_rom, project_to_rom

# =========================================================================
# DEVICE SETUP & CONFIGURATION
# =========================================================================
print("torch version:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu")
print(f"Using {device} device")

torch.cuda.manual_seed(42)

csv_internal_test_path = 'Bases/dataset_operator_internal_train.csv'
csv_boundary_test_path = 'Bases/dataset_operator_boundary_train.csv'

csv_internal_train_path = 'Bases/dataset_operator_internal_train.csv'
csv_boundary_train_path = 'Bases/dataset_operator_boundary_train.csv'
npz_rom_path = 'Bases/hdg_rom_bases.npz'
models_dir = 'trained_operators'
use_single_stage = True  # If False, uses a two-stage optimization approach
use_non_true_bnd = False  # If True, initializes boundary values to zero instead of true values

n_subx, n_suby = 8, 8

# =========================================================================
# HELPER FUNCTIONS
# =========================================================================
def load_model(model_name: str, input_dim: int, output_dim: int, hidden_dims=(64, 128, 64, 32)) -> nn.Module:
    """Load a DD_HDG_Trainer model exactly as defined in dd_hdg_training8.py."""
    model_path = os.path.join(models_dir, f"{model_name}_model.pth")
    model = DD_HDG_Trainer(input_dim=input_dim, output_dim=output_dim, hidden_dims=hidden_dims)
    state_dict = torch.load(model_path, map_location=device)
    model.load_state_dict(state_dict)
    model.to(device)
    model.eval()
    return model

def load_scalers(model_name: str):
    """Load input and output standard scalers based on training script naming."""
    scaler_path = os.path.join(models_dir, f"{model_name}_scalers.pkl")
    with open(scaler_path, "rb") as scaler_file:
        scalers = pickle.load(scaler_file)
    return scalers["x_scaler"], scalers["y_scaler"]

def load_svd_bases(npz_path: str):
    """Load SVD bases directly from the .npz file generated by dd_hdg_SVD2.py."""
    if not os.path.exists(npz_path):
        raise FileNotFoundError(f"Missing {npz_path}. Run dd_hdg_SVD2.py first.")
    return np.load(npz_path)

def load_combined_data_stacked(
    internal_path: str,
    boundary_path: str,
    operator: str = 'solution',
    flux_direction: str = None,
    sample_index: int = 0
):
    """Stacks internal and boundary subdomains vertically under unified headers,
    preserves spatial sorting, and handles domain-specific columns.
    """
    df_int = pd.read_csv(internal_path)
    df_bnd = pd.read_csv(boundary_path)

    # Harmonize column prefixes so headers match across both files
    df_int = df_int.rename(columns=lambda x: x.replace('F_sub_1_', 'F_sub_').replace('U_sub_1_', 'U_sub_'))
    df_bnd = df_bnd.rename(columns=lambda x: x.replace('F_sub_2_', 'F_sub_').replace('U_sub_2_', 'U_sub_'))

    if 'sample_index' in df_int.columns:
        df_int = df_int[df_int['sample_index'] == sample_index]
        df_bnd = df_bnd[df_bnd['sample_index'] == sample_index]

    # Domain flags
    df_int['is_boundary_domain'] = False
    df_bnd['is_boundary_domain'] = True

    # Stack vertically
    stacked_df = pd.concat([df_int, df_bnd], axis=0, ignore_index=True)

    # Sort spatially by mesh coordinates
    if 'ny_index' in stacked_df.columns and 'nx_index' in stacked_df.columns:
        stacked_df = stacked_df.sort_values(by=['ny_index', 'nx_index']).reset_index(drop=True)

    f_e_cols = [c for c in stacked_df.columns if 'F_sub_' in c and 'mode_' in c]
    bnd_flag_cols = [c for c in stacked_df.columns if ('U_face_' in c or 'U_corners_' in c) and '_is_bnd' in c]

    stacked_df[bnd_flag_cols] = stacked_df[bnd_flag_cols].fillna(0.0)

    X_f = stacked_df[f_e_cols].values
    X_bnd = stacked_df[bnd_flag_cols].values
    is_bnd_mask = stacked_df['is_boundary_domain'].values

    if operator == 'solution':
        u_e_cols = [c for c in stacked_df.columns if 'U_sub_' in c and 'mode_' in c]
        y = stacked_df[u_e_cols].values
    elif operator == 'flux':
        target_cols = [c for c in stacked_df.columns if f'J_face_{flux_direction}_' in c and 'mode_' in c]
        y = stacked_df[target_cols].values

    return X_f, X_bnd, y, stacked_df, is_bnd_mask

def create_face_lookup(n_subx: int, n_suby: int):
    horizontal_id = {(ix, iy): uid for uid, (ix, iy) in enumerate([(x, y) for y in range(n_suby + 1) for x in range(n_subx)])}
    vertical_id = {(ix, iy): uid + len(horizontal_id) for uid, (ix, iy) in enumerate([(x, y) for y in range(n_suby) for x in range(n_subx + 1)])}

    rows = []
    for nx in range(n_subx):
        for ny in range(n_suby):
            rows.extend([
                (nx, ny, 'bottom', horizontal_id[(nx, ny)]),
                (nx, ny, 'top', horizontal_id[(nx, ny + 1)]),
                (nx, ny, 'left', vertical_id[(nx, ny)]),
                (nx, ny, 'right', vertical_id[(nx + 1, ny)])
            ])
    return rows, pd.DataFrame(rows, columns=['nx_index', 'ny_index', 'direction', 'n_unique'])

def create_corner_lookup(n_subx: int, n_suby: int):
    corner_id = {(ix, iy): uid for uid, (ix, iy) in enumerate([(x, y) for y in range(n_suby + 1) for x in range(n_subx + 1)])}
    rows = []
    for ny in range(n_suby):
        for nx in range(n_subx):
            rows.extend([
                (nx, ny, 'bottom_left', corner_id[(nx, ny)]),
                (nx, ny, 'bottom_right', corner_id[(nx + 1, ny)]),
                (nx, ny, 'top_left', corner_id[(nx, ny + 1)]),
                (nx, ny, 'top_right', corner_id[(nx + 1, ny + 1)])
            ])
    return rows, pd.DataFrame(rows, columns=['nx_index', 'ny_index', 'corner_position', 'n_unique'])
def reconstruct_full_solution(
    predicted_rom_modes, 
    is_bnd_mask, 
    rom_data, 
    n_subx=8, 
    n_suby=8, 
    sub_ny=9, 
    sub_nx=9
):
    """
    Reconstructs the full 2D physical field from predicted subdomain ROM modes,
    handling boundary (`U_sub_bnd`) and internal (`U_sub_int`) bases separately.
    
    Parameters
    ----------
    predicted_rom_modes : np.ndarray
        Array of shape (n_subdomains, k) containing the predicted ROM coefficients.
    is_bnd_mask : np.ndarray or torch.Tensor
        Boolean array of shape (n_subdomains,) where True indicates a boundary subdomain.
    rom_data : dict-like (np.lib.npyio.NpzFile or dict)
        Loaded SVD basis dictionary containing:
        - 'U_sub_int_basis', 'U_sub_int_mean'
        - 'U_sub_bnd_basis', 'U_sub_bnd_mean'
    n_subx, n_suby : int
        Number of subdomains in x and y directions.
    sub_ny, sub_nx : int
        Number of physical nodes inside each subdomain patch (e.g., 9x9 for 8x8 elements).
        
    Returns
    -------
    U_full : np.ndarray
        The reconstructed global 2D physical domain solution of shape (G_ny, G_nx).
    """
    if hasattr(is_bnd_mask, 'cpu'):
        is_bnd_mask = is_bnd_mask.cpu().numpy()
        
    is_bnd_mask = is_bnd_mask.astype(bool)
    is_int_mask = ~is_bnd_mask

    # Extract SVD bases and mean vectors
    U_sub_int_basis = rom_data["U_sub_int_basis"]  # Shape: (sub_ny * sub_nx, k)
    U_sub_int_mean  = rom_data["U_sub_int_mean"]   # Shape: (1, sub_ny * sub_nx)
    U_sub_bnd_basis = rom_data["U_sub_bnd_basis"]  # Shape: (sub_ny * sub_nx, k)
    U_sub_bnd_mean  = rom_data["U_sub_bnd_mean"]   # Shape: (1, sub_ny * sub_nx)

    num_elements = predicted_rom_modes.shape[0]
    feature_dim = sub_ny * sub_nx
    U_sub_reconstructed = np.zeros((num_elements, feature_dim), dtype=np.float32)

    # Reconstruct internal subdomains: U = Coeffs @ Basis^T + Mean
    if np.any(is_int_mask):
        U_sub_reconstructed[is_int_mask] = (
            predicted_rom_modes[is_int_mask] @ U_sub_int_basis.T
        ) + U_sub_int_mean

    # Reconstruct boundary subdomains: U = Coeffs @ Basis^T + Mean
    if np.any(is_bnd_mask):
        U_sub_reconstructed[is_bnd_mask] = (
            predicted_rom_modes[is_bnd_mask] @ U_sub_bnd_basis.T
        ) + U_sub_bnd_mean

    # Reshape reconstructed rows into (n_suby, n_subx, sub_ny, sub_nx)
    U_patches = U_sub_reconstructed.reshape(n_suby, n_subx, sub_ny, sub_nx)

    # Stitch patches into the global 2D physical grid (accounting for shared interface nodes)
    G_ny = n_suby * (sub_ny - 1) + 1
    G_nx = n_subx * (sub_nx - 1) + 1

    U_full = np.zeros((G_ny, G_nx), dtype=np.float32)
    weights = np.zeros((G_ny, G_nx), dtype=np.float32)

    for iy in range(n_suby):
        y_start = iy * (sub_ny - 1)
        y_end = y_start + sub_ny
        for ix in range(n_subx):
            x_start = ix * (sub_nx - 1)
            x_end = x_start + sub_nx

            U_full[y_start:y_end, x_start:x_end] += U_patches[iy, ix]
            weights[y_start:y_end, x_start:x_end] += 1.0

    # Average interface values shared between adjacent subdomains
    U_full /= weights

    return U_full
# =========================================================================
# 1. LOAD DATA & MODELS
# =========================================================================
sample_idx = 5
print(f"Loading full domain for Sample Index: {sample_idx}")

x_f, x_bnd, y_S, sample_df, is_bnd_mask = load_combined_data_stacked(
    csv_internal_test_path, csv_boundary_test_path, operator='solution', sample_index=sample_idx
)

_, _, y_J_left, _, _   = load_combined_data_stacked(csv_internal_test_path, csv_boundary_test_path, operator='flux', flux_direction='left', sample_index=sample_idx)
_, _, y_J_right, _, _  = load_combined_data_stacked(csv_internal_test_path, csv_boundary_test_path, operator='flux', flux_direction='right', sample_index=sample_idx)
_, _, y_J_top, _, _    = load_combined_data_stacked(csv_internal_test_path, csv_boundary_test_path, operator='flux', flux_direction='top', sample_index=sample_idx)
_, _, y_J_bottom, _, _ = load_combined_data_stacked(csv_internal_test_path, csv_boundary_test_path, operator='flux', flux_direction='bottom', sample_index=sample_idx)

bnd_mask = torch.tensor(is_bnd_mask, dtype=torch.bool, device=device)
int_mask = ~bnd_mask

X_f_const   = torch.tensor(x_f, dtype=torch.float32, device=device)
X_bnd_const = torch.tensor(x_bnd, dtype=torch.float32, device=device)

latent_face_dim   =4
latent_corner_dim = 1
in_dim = 3 + (4 * latent_face_dim) + (4 * latent_corner_dim) + x_bnd.shape[1] # 19

# Load Internal Models
S_int        = load_model("solution_internal8", input_dim=in_dim, output_dim=y_S.shape[1], hidden_dims=(64, 32))
J_left_int   = load_model("flux_internal8_left", input_dim=in_dim, output_dim=y_J_left.shape[1], hidden_dims=(64, 128, 64, 32))
J_right_int  = load_model("flux_internal8_right", input_dim=in_dim, output_dim=y_J_right.shape[1], hidden_dims=(64, 128, 64, 32))
J_top_int    = load_model("flux_internal8_top", input_dim=in_dim, output_dim=y_J_top.shape[1], hidden_dims=(64, 128, 64, 32))
J_bottom_int = load_model("flux_internal8_bottom", input_dim=in_dim, output_dim=y_J_bottom.shape[1], hidden_dims=(64, 128, 64, 32))

# Load Boundary Models
S_bnd        = load_model("solution_boundary8", input_dim=in_dim, output_dim=y_S.shape[1], hidden_dims=(64, 32))
J_left_bnd   = load_model("flux_boundary8_left", input_dim=in_dim, output_dim=y_J_left.shape[1], hidden_dims=(64, 128, 64, 32))
J_right_bnd  = load_model("flux_boundary8_right", input_dim=in_dim, output_dim=y_J_right.shape[1], hidden_dims=(64, 128, 64, 32))
J_top_bnd    = load_model("flux_boundary8_top", input_dim=in_dim, output_dim=y_J_top.shape[1], hidden_dims=(64, 128, 64, 32))
J_bottom_bnd = load_model("flux_boundary8_bottom", input_dim=in_dim, output_dim=y_J_bottom.shape[1], hidden_dims=(64, 128, 64, 32))

# Load Scalers
x_scaler_int, y_scaler_S_int = load_scalers("solution_internal8")
x_scaler_bnd, y_scaler_S_bnd = load_scalers("solution_boundary8")

x_mean_int  = torch.tensor(x_scaler_int.mean_, dtype=torch.float32, device=device)
x_scale_int = torch.tensor(x_scaler_int.scale_, dtype=torch.float32, device=device)
x_mean_bnd  = torch.tensor(x_scaler_bnd.mean_, dtype=torch.float32, device=device)
x_scale_bnd = torch.tensor(x_scaler_bnd.scale_, dtype=torch.float32, device=device)

unscale_dict_int = {
    'left':   (torch.tensor(load_scalers("flux_internal8_left")[1].scale_, dtype=torch.float32, device=device),   torch.tensor(load_scalers("flux_internal8_left")[1].mean_, dtype=torch.float32, device=device)),
    'right':  (torch.tensor(load_scalers("flux_internal8_right")[1].scale_, dtype=torch.float32, device=device),  torch.tensor(load_scalers("flux_internal8_right")[1].mean_, dtype=torch.float32, device=device)),
    'top':    (torch.tensor(load_scalers("flux_internal8_top")[1].scale_, dtype=torch.float32, device=device),    torch.tensor(load_scalers("flux_internal8_top")[1].mean_, dtype=torch.float32, device=device)),
    'bottom': (torch.tensor(load_scalers("flux_internal8_bottom")[1].scale_, dtype=torch.float32, device=device), torch.tensor(load_scalers("flux_internal8_bottom")[1].mean_, dtype=torch.float32, device=device))
}

unscale_dict_bnd = {
    'left':   (torch.tensor(load_scalers("flux_boundary8_left")[1].scale_, dtype=torch.float32, device=device),   torch.tensor(load_scalers("flux_boundary8_left")[1].mean_, dtype=torch.float32, device=device)),
    'right':  (torch.tensor(load_scalers("flux_boundary8_right")[1].scale_, dtype=torch.float32, device=device),  torch.tensor(load_scalers("flux_boundary8_right")[1].mean_, dtype=torch.float32, device=device)),
    'top':    (torch.tensor(load_scalers("flux_boundary8_top")[1].scale_, dtype=torch.float32, device=device),    torch.tensor(load_scalers("flux_boundary8_top")[1].mean_, dtype=torch.float32, device=device)),
    'bottom': (torch.tensor(load_scalers("flux_boundary8_bottom")[1].scale_, dtype=torch.float32, device=device), torch.tensor(load_scalers("flux_boundary8_bottom")[1].mean_, dtype=torch.float32, device=device))
}

rom_data = load_svd_bases(npz_rom_path)
U_sub_int_basis   = rom_data["U_sub_int_basis"]
U_sub_int_mean    = rom_data["U_sub_int_mean"]
F_sub_int_basis   = rom_data["F_sub_int_basis"]
F_sub_int_mean    = rom_data["F_sub_int_mean"]
J_face_int_basis  = rom_data["J_face_int_basis"]
J_face_int_mean   = rom_data["J_face_int_mean"]
U_face_int_basis  = rom_data["U_face_int_basis"]
U_face_int_mean   = rom_data["U_face_int_mean"]
U_corners_int_mean= rom_data["U_corners_int_mean"]

U_sub_bnd_basis   = rom_data["U_sub_bnd_basis"]
U_sub_bnd_mean    = rom_data["U_sub_bnd_mean"]
F_sub_bnd_basis   = rom_data["F_sub_bnd_basis"]
F_sub_bnd_mean    = rom_data["F_sub_bnd_mean"]
J_face_bnd_basis  = rom_data["J_face_bnd_basis"]
J_face_bnd_mean   = rom_data["J_face_bnd_mean"]
U_face_bnd_basis  = rom_data["U_face_bnd_basis"]
U_face_bnd_mean   = rom_data["U_face_bnd_mean"]
U_corners_bnd_mean= rom_data["U_corners_bnd_mean"]

# =========================================================================
# 2. MESH TOPOLOGY, INDEXING & GROUND-TRUTH EXTRACTION
# =========================================================================
face_rows, face_lookup_df = create_face_lookup(n_subx, n_suby)
corner_rows, corner_lookup_df = create_corner_lookup(n_subx, n_suby)

n_corners = (n_subx + 1) * (n_suby + 1)
n_faces = (n_subx + 1) * n_suby + n_subx * (n_suby + 1)

# --- Identify Boundary Faces ---
is_global_bottom = (face_lookup_df['ny_index'] == 0) & (face_lookup_df['direction'] == 'bottom')
is_global_top    = (face_lookup_df['ny_index'] == n_suby - 1) & (face_lookup_df['direction'] == 'top')
is_global_left   = (face_lookup_df['nx_index'] == 0) & (face_lookup_df['direction'] == 'left')
is_global_right  = (face_lookup_df['nx_index'] == n_subx - 1) & (face_lookup_df['direction'] == 'right')

idx_bnd_bottom = torch.tensor(face_lookup_df[is_global_bottom]['n_unique'].values, dtype=torch.long, device=device)
idx_bnd_top    = torch.tensor(face_lookup_df[is_global_top]['n_unique'].values, dtype=torch.long, device=device)
idx_bnd_left   = torch.tensor(face_lookup_df[is_global_left]['n_unique'].values, dtype=torch.long, device=device)
idx_bnd_right  = torch.tensor(face_lookup_df[is_global_right]['n_unique'].values, dtype=torch.long, device=device)

global_boundary_indices = torch.cat([idx_bnd_bottom, idx_bnd_top, idx_bnd_left, idx_bnd_right])

all_indices = np.arange(n_faces)
is_internal = ~np.isin(all_indices, global_boundary_indices.cpu().numpy())
internal_indices = torch.tensor(all_indices[is_internal], dtype=torch.long, device=device)

# --- Identify Boundary Corners ---
is_global_corner_bottom = (corner_lookup_df['ny_index'] == 0) & (corner_lookup_df['corner_position'].isin(['bottom_left', 'bottom_right']))
is_global_corner_top    = (corner_lookup_df['ny_index'] == n_suby - 1) & (corner_lookup_df['corner_position'].isin(['top_left', 'top_right']))
is_global_corner_left   = (corner_lookup_df['nx_index'] == 0) & (corner_lookup_df['corner_position'].isin(['bottom_left', 'top_left']))
is_global_corner_right  = (corner_lookup_df['nx_index'] == n_subx - 1) & (corner_lookup_df['corner_position'].isin(['bottom_right', 'top_right']))

is_global_corner_mask = (is_global_corner_bottom | is_global_corner_top | is_global_corner_left | is_global_corner_right)
global_corner_indices = torch.tensor(corner_lookup_df[is_global_corner_mask]['n_unique'].values, dtype=torch.long, device=device)

# --- A. EXTRACT REAL PHYSICAL BOUNDARY FACES ---
bottom_df = sample_df[sample_df['ny_index'] == 0].sort_values(by='nx_index')
true_bottom = torch.tensor(bottom_df[['U_face_bottom_mode_0', 'U_face_bottom_mode_1', 'U_face_bottom_mode_2','U_face_bottom_mode_3']].values, dtype=torch.float32, device=device)
if use_non_true_bnd:
    true_bottom = torch.tensor(project_to_rom(np.zeros((bottom_df.shape[0], 5)), U_face_bnd_basis, U_face_bnd_mean), dtype=torch.float32, device=device)

top_df = sample_df[sample_df['ny_index'] == n_suby - 1].sort_values(by='nx_index')
true_top = torch.tensor(top_df[['U_face_top_mode_0', 'U_face_top_mode_1', 'U_face_top_mode_2','U_face_top_mode_3']].values, dtype=torch.float32, device=device)
if use_non_true_bnd:
    true_top = torch.tensor(project_to_rom(np.zeros((top_df.shape[0], 5)), U_face_bnd_basis, U_face_bnd_mean), dtype=torch.float32, device=device)

left_df = sample_df[sample_df['nx_index'] == 0].sort_values(by='ny_index')
true_left = torch.tensor(left_df[['U_face_left_mode_0', 'U_face_left_mode_1', 'U_face_left_mode_2','U_face_left_mode_3']].values, dtype=torch.float32, device=device)
if use_non_true_bnd:
    true_left = torch.tensor(project_to_rom(np.zeros((left_df.shape[0], 5)), U_face_bnd_basis, U_face_bnd_mean), dtype=torch.float32, device=device)

right_df = sample_df[sample_df['nx_index'] == n_subx - 1].sort_values(by='ny_index')
true_right = torch.tensor(right_df[['U_face_right_mode_0', 'U_face_right_mode_1', 'U_face_right_mode_2','U_face_right_mode_3']].values, dtype=torch.float32, device=device)
if use_non_true_bnd:
    true_right = torch.tensor(project_to_rom(np.zeros((right_df.shape[0], 5)), U_face_bnd_basis, U_face_bnd_mean), dtype=torch.float32, device=device)

true_global_boundaries = torch.cat([true_bottom, true_top, true_left, true_right])

# --- B. EXTRACT REAL PHYSICAL BOUNDARY CORNERS ---
global_corners_df = corner_lookup_df[is_global_corner_mask]
true_corners_list = []

for _, row in global_corners_df.iterrows():
    nx = row['nx_index']
    ny = row['ny_index']
    pos = row['corner_position']
    subelement = sample_df[(sample_df['nx_index'] == nx) & (sample_df['ny_index'] == ny)]
    corner_val = subelement[f'U_corners_{pos}_mode_0'].values[0]
    true_corners_list.append([corner_val])

true_global_corners = torch.tensor(true_corners_list, dtype=torch.float32, device=device)
if use_non_true_bnd:
    true_global_corners = torch.tensor(np.zeros((len(true_corners_list), 5)) - U_corners_bnd_mean, dtype=torch.float32, device=device)

# --- Routing Index Pairs ---
U_dummy = np.zeros((n_subx, n_suby, 2, 2, 1)) 
neighbours = extract_neighbours_indexes(U_dummy)

vertical_match_A, vertical_match_B, horizontal_match_C, horizontal_match_D = [], [], [], []
for iy in range(n_suby):
    for ix in range(n_subx):
        curr_id = iy * n_subx + ix
        if neighbours[iy, ix]['right'] != -1:
            vertical_match_A.append(curr_id)
            vertical_match_B.append(neighbours[iy, ix]['right'])
        if neighbours[iy, ix]['top'] != -1:
            horizontal_match_C.append(curr_id)
            horizontal_match_D.append(neighbours[iy, ix]['top'])

idx_batch_right_face  = torch.tensor(vertical_match_A, dtype=torch.long, device=device)
idx_batch_left_face   = torch.tensor(vertical_match_B, dtype=torch.long, device=device)
idx_batch_bottom_face = torch.tensor(horizontal_match_C, dtype=torch.long, device=device)
idx_batch_top_face    = torch.tensor(horizontal_match_D, dtype=torch.long, device=device)

idx_dict = {
    'bottom': torch.tensor(face_lookup_df[face_lookup_df['direction'] == 'bottom'].sort_values(by=['ny_index', 'nx_index'])['n_unique'].values, device=device),
    'right':  torch.tensor(face_lookup_df[face_lookup_df['direction'] == 'right'].sort_values(by=['ny_index', 'nx_index'])['n_unique'].values, device=device),
    'top':    torch.tensor(face_lookup_df[face_lookup_df['direction'] == 'top'].sort_values(by=['ny_index', 'nx_index'])['n_unique'].values, device=device),
    'left':   torch.tensor(face_lookup_df[face_lookup_df['direction'] == 'left'].sort_values(by=['ny_index', 'nx_index'])['n_unique'].values, device=device),
    'bl':     torch.tensor(corner_lookup_df[corner_lookup_df['corner_position'] == 'bottom_left'].sort_values(by=['ny_index', 'nx_index'])['n_unique'].values, device=device),
    'br':     torch.tensor(corner_lookup_df[corner_lookup_df['corner_position'] == 'bottom_right'].sort_values(by=['ny_index', 'nx_index'])['n_unique'].values, device=device),
    'tl':     torch.tensor(corner_lookup_df[corner_lookup_df['corner_position'] == 'top_left'].sort_values(by=['ny_index', 'nx_index'])['n_unique'].values, device=device),
    'tr':     torch.tensor(corner_lookup_df[corner_lookup_df['corner_position'] == 'top_right'].sort_values(by=['ny_index', 'nx_index'])['n_unique'].values, device=device)
}

# =========================================================================
# 3. INITIALIZE PARAMETERS VIA BEST-MATCHING TRAIN SAMPLE (MIN RELATIVE F_sub ERROR)
# =========================================================================
print("\n--- INITIALIZING VIA BEST F_sub MATCH IN TRAINING DATABASE ---")

df_train_int = pd.read_csv(csv_internal_train_path)
df_train_bnd = pd.read_csv(csv_boundary_train_path)

df_train_int = df_train_int.rename(columns=lambda x: x.replace('F_sub_1_', 'F_sub_').replace('U_sub_1_', 'U_sub_'))
df_train_bnd = df_train_bnd.rename(columns=lambda x: x.replace('F_sub_2_', 'F_sub_').replace('U_sub_2_', 'U_sub_'))

df_train = pd.concat([df_train_int, df_train_bnd], axis=0, ignore_index=True)
df_train = df_train.sort_values(by=['sample_index', 'ny_index', 'nx_index']).reset_index(drop=True)

f_cols = [c for c in df_train.columns if 'F_sub_' in c and 'mode_' in c]
train_samples = df_train['sample_index'].unique()

query_F_vec = X_f_const.cpu().numpy().ravel()

best_sample_id = None
min_rel_err = float('inf')

for s_id in train_samples:
    s_df = df_train[df_train['sample_index'] == s_id]
    cand_F_vec = s_df[f_cols].values.ravel()
    
    rel_err = np.linalg.norm(query_F_vec - cand_F_vec) / (np.linalg.norm(query_F_vec) + 1e-15)
    
    if rel_err < min_rel_err:
        min_rel_err = rel_err
        best_sample_id = s_id

print(f" -> Best matching train sample ID: {best_sample_id} | Relative F_sub Error: {min_rel_err:.4e}")

best_df = df_train[df_train['sample_index'] == best_sample_id].sort_values(by=['ny_index', 'nx_index']).reset_index(drop=True)

init_face_values = np.zeros((n_faces, 4), dtype=np.float32)
init_corner_values = np.zeros((n_corners, 1), dtype=np.float32)

for _, row in face_lookup_df.iterrows():
    nx, ny = int(row['nx_index']), int(row['ny_index'])
    direction = row['direction']
    uid = int(row['n_unique'])
    
    sub_row = best_df[(best_df['nx_index'] == nx) & (best_df['ny_index'] == ny)]
    for i in range(4):
        val = sub_row[f'U_face_{direction}_mode_{i}'].values[0]
        init_face_values[uid, i] = val

for _, row in corner_lookup_df.iterrows():
    nx, ny = int(row['nx_index']), int(row['ny_index'])
    pos = row['corner_position']
    uid = int(row['n_unique'])
    
    sub_row = best_df[(best_df['nx_index'] == nx) & (best_df['ny_index'] == ny)]
    for i in range(1):
        val = sub_row[f'U_corners_{pos}_mode_{i}'].values[0]
        init_corner_values[uid, i] = val

# Enforce target boundary conditions
#init_face_values[idx_bnd_bottom.cpu().numpy()] = true_bottom.cpu().numpy()
#init_face_values[idx_bnd_top.cpu().numpy()]    = true_top.cpu().numpy()
#init_face_values[idx_bnd_left.cpu().numpy()]   = true_left.cpu().numpy()
#init_face_values[idx_bnd_right.cpu().numpy()]  = true_right.cpu().numpy()

#init_corner_values[global_corner_indices.cpu().numpy()] = true_global_corners.cpu().numpy()

face_values = torch.tensor(init_face_values, dtype=torch.float32, device=device).requires_grad_()
corner_values = torch.tensor(init_corner_values, dtype=torch.float32, device=device).requires_grad_()

# =========================================================================
# 4. OPTIMIZATION CORE (L-BFGS ON ALL VARIABLES)
# =========================================================================
loss_fn = nn.MSELoss(reduction='mean')
weights = {'interior': 1, 'face': 0, 'corner': 0}

def compute_fluxes_routed():
    f_bot = face_values[idx_dict['bottom']]
    f_rig = face_values[idx_dict['right']]
    f_top = face_values[idx_dict['top']]
    f_lef = face_values[idx_dict['left']]
    
    c_bl = corner_values[idx_dict['bl']]
    c_br = corner_values[idx_dict['br']]
    c_tr = corner_values[idx_dict['tr']]
    c_tl = corner_values[idx_dict['tl']]

    # 1. Internal Elements
    X_int = torch.cat([
        X_f_const[int_mask], 
        f_bot[int_mask], f_rig[int_mask], f_top[int_mask], f_lef[int_mask],
        c_bl[int_mask], c_br[int_mask], c_tr[int_mask], c_tl[int_mask],
        X_bnd_const[int_mask]
    ], dim=1)
    X_int_scaled = (X_int - x_mean_int) / x_scale_int

    # 2. Boundary Elements
    X_bnd_elem = torch.cat([
        X_f_const[bnd_mask], 
        f_bot[bnd_mask], f_rig[bnd_mask], f_top[bnd_mask], f_lef[bnd_mask],
        c_bl[bnd_mask], c_br[bnd_mask], c_tr[bnd_mask], c_tl[bnd_mask],
        X_bnd_const[bnd_mask]
    ], dim=1)
    X_bnd_scaled = (X_bnd_elem - x_mean_bnd) / x_scale_bnd

    flux_left_int   = (J_left_int(X_int_scaled) * unscale_dict_int['left'][0]) + unscale_dict_int['left'][1]
    flux_right_int  = (J_right_int(X_int_scaled) * unscale_dict_int['right'][0]) + unscale_dict_int['right'][1]
    flux_top_int    = (J_top_int(X_int_scaled) * unscale_dict_int['top'][0]) + unscale_dict_int['top'][1]
    flux_bottom_int = (J_bottom_int(X_int_scaled) * unscale_dict_int['bottom'][0]) + unscale_dict_int['bottom'][1]

    flux_left_bnd   = (J_left_bnd(X_bnd_scaled) * unscale_dict_bnd['left'][0]) + unscale_dict_bnd['left'][1]
    flux_right_bnd  = (J_right_bnd(X_bnd_scaled) * unscale_dict_bnd['right'][0]) + unscale_dict_bnd['right'][1]
    flux_top_bnd    = (J_top_bnd(X_bnd_scaled) * unscale_dict_bnd['top'][0]) + unscale_dict_bnd['top'][1]
    flux_bottom_bnd = (J_bottom_bnd(X_bnd_scaled) * unscale_dict_bnd['bottom'][0]) + unscale_dict_bnd['bottom'][1]

    num_elements = X_f_const.shape[0]

    flux_left   = torch.empty((num_elements, flux_left_int.shape[1]), dtype=torch.float32, device=device)
    flux_left[int_mask] = flux_left_int
    flux_left[bnd_mask] = flux_left_bnd

    flux_right  = torch.empty((num_elements, flux_right_int.shape[1]), dtype=torch.float32, device=device)
    flux_right[int_mask] = flux_right_int
    flux_right[bnd_mask] = flux_right_bnd

    flux_top    = torch.empty((num_elements, flux_top_int.shape[1]), dtype=torch.float32, device=device)
    flux_top[int_mask] = flux_top_int
    flux_top[bnd_mask] = flux_top_bnd

    flux_bottom = torch.empty((num_elements, flux_bottom_int.shape[1]), dtype=torch.float32, device=device)
    flux_bottom[int_mask] = flux_bottom_int
    flux_bottom[bnd_mask] = flux_bottom_bnd

    loss_vertical   = loss_fn(flux_right[idx_batch_right_face], -flux_left[idx_batch_left_face])
    loss_horizontal = loss_fn(flux_top[idx_batch_top_face], -flux_bottom[idx_batch_bottom_face])

    reg_loss = loss_fn(face_values, torch.tensor(init_face_values, device=device)) + \
           loss_fn(corner_values, torch.tensor(init_corner_values, device=device))

    face_boundary_loss   = loss_fn(face_values[global_boundary_indices], true_global_boundaries)
    corner_boundary_loss = loss_fn(corner_values[global_corner_indices], true_global_corners)

    total_loss = weights['interior'] * (loss_vertical + loss_horizontal) + weights['face'] * face_boundary_loss + weights['corner'] * corner_boundary_loss + 1e-2 * reg_loss
    return total_loss, loss_vertical, loss_horizontal ,face_boundary_loss, corner_boundary_loss

print("\n--- OPTIMIZATION: L-BFGS (ALL FACES & CORNERS) ---")
optimizer_lbfgs = torch.optim.LBFGS([face_values, corner_values], lr=1.0, max_iter=50, line_search_fn='strong_wolfe')

def closure():
    optimizer_lbfgs.zero_grad()
    total_loss, _, _ ,l_face, l_corner= compute_fluxes_routed()
    total_loss.backward()
    return total_loss

if use_single_stage:
    for epoch in range(100):
        optimizer_lbfgs.step(closure)
        total_loss, l_vert, l_horz ,l_face, l_corner= compute_fluxes_routed()
        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f"Epoch {epoch + 1:02d} | Total Loss: {total_loss.item():.6e} | Vert: {l_vert.item():.6e} | Horz: {l_horz.item():.6e} | Face: {l_face.item():.6e} | Corner: {l_corner.item():.6e}")
        if total_loss.item() < 1e-4:
            print(f"Converged at Epoch {epoch + 1:02d} with Total Loss: {total_loss.item():.6e}")
            break

    #print(f"Final Optimization Loss: {total_loss.item():.6e} | Vert: {l_vert.item():.6e} | Horz: {l_horz.item():.6e}")
else:
    # STAGE 1
    print("\n--- STAGE 1: Aligning Faces and Interior Fluxes ---")
    weights = {'interior': 1, 'face': 100, 'corner': 100}
    optimizer = torch.optim.LBFGS([face_values, corner_values], lr=1.0, max_iter=50, line_search_fn='strong_wolfe')

    for epoch in range(50):
        current_loss = optimizer.step(closure)
        total_loss, vertical_loss, horizontal_loss ,face_loss, corner_loss = compute_fluxes_routed()
        if epoch % 10 == 0 or epoch == 49:
            print(f"Stage 1 | Epoch {epoch} | Loss: {current_loss.item():.6e} | Vertical: {vertical_loss.item():.6e} | Horizontal: {horizontal_loss.item():.6e} | Face: {face_loss.item():.6e} | Corner: {corner_loss.item():.6e}")

    # STAGE 2
    print("\n--- STAGE 2: Pounding Down Stubborn boundary Errors ---")
    weights = {'interior': 1, 'face': 1, 'corner': 1}
    optimizer = torch.optim.LBFGS([face_values, corner_values], lr=1.0, max_iter=50, line_search_fn='strong_wolfe')
    for epoch in range(50):
        current_loss = optimizer.step(closure)
        total_loss, vertical_loss, horizontal_loss ,face_loss, corner_loss = compute_fluxes_routed()
        if epoch % 10 == 0 or epoch == 49:
            print(f"Stage 2 | Epoch {epoch} | Loss: {current_loss.item():.6e} | Vertical: {vertical_loss.item():.6e} | Horizontal: {horizontal_loss.item():.6e} | Face: {face_loss.item():.6e} | Corner: {corner_loss.item():.6e}")

# Evaluate predicted flux residuals on the TRUE physical interface modes
with torch.no_grad():
  total_loss, loss_vert, loss_horz ,l_face, l_corner= compute_fluxes_routed()
  print(
      f"Flux Residual on True Interface Modes: Vert = {loss_vert.item():.6e} |"
      f" Horz = {loss_horz.item():.6e} | Face = {l_face.item():.6e} | Corner = {l_corner.item():.6e}"
  )
# =========================================================================
# 5. FINAL INFERENCE & RECONSTRUCTION
# =========================================================================
print("\n--- FINAL RECONSTRUCTION ---")
with torch.no_grad():
    f_bot = face_values[idx_dict['bottom']]
    f_rig = face_values[idx_dict['right']]
    f_top = face_values[idx_dict['top']]
    f_lef = face_values[idx_dict['left']]
    
    c_bl = corner_values[idx_dict['bl']]
    c_br = corner_values[idx_dict['br']]
    c_tr = corner_values[idx_dict['tr']]
    c_tl = corner_values[idx_dict['tl']]

    # 1. Evaluate Internal Subdomains
    X_int_final = torch.cat([
        X_f_const[int_mask], 
        f_bot[int_mask], f_rig[int_mask], f_top[int_mask], f_lef[int_mask],
        c_bl[int_mask], c_br[int_mask], c_tr[int_mask], c_tl[int_mask],
        X_bnd_const[int_mask]
    ], dim=1)
    X_int_final_scaled = (X_int_final - x_mean_int) / x_scale_int
    sol_int_scaled = S_int(X_int_final_scaled)

    # 2. Evaluate Boundary Subdomains
    X_bnd_final = torch.cat([
        X_f_const[bnd_mask], 
        f_bot[bnd_mask], f_rig[bnd_mask], f_top[bnd_mask], f_lef[bnd_mask],
        c_bl[bnd_mask], c_br[bnd_mask], c_tr[bnd_mask], c_tl[bnd_mask],
        X_bnd_const[bnd_mask]
    ], dim=1)
    X_bnd_final_scaled = (X_bnd_final - x_mean_bnd) / x_scale_bnd
    sol_bnd_scaled = S_bnd(X_bnd_final_scaled)

    # Inverse transform to predicted ROM modes space
    sol_int_modes = y_scaler_S_int.inverse_transform(sol_int_scaled.cpu().numpy())
    sol_bnd_modes = y_scaler_S_bnd.inverse_transform(sol_bnd_scaled.cpu().numpy())

    # Assemble full mesh ROM predicted modes
    num_elements = X_f_const.shape[0]
    num_modes = sol_int_modes.shape[1]
    predicted_rom_modes = np.zeros((num_elements, num_modes))
    predicted_rom_modes[int_mask.cpu().numpy()] = sol_int_modes
    predicted_rom_modes[bnd_mask.cpu().numpy()] = sol_bnd_modes

    target_rom_modes = y_S

# =========================================================================
# COMPARE PREDICTED VS TARGET ROM MODES
# =========================================================================
print("\n--- ROM MODES DIAGNOSTICS ---")
print(f"Target ROM modes shape: {target_rom_modes.shape}")
print(f"Pred ROM modes shape:   {predicted_rom_modes.shape}")

print(f"Min/Max of Target ROM modes: {np.min(target_rom_modes):.6f} / {np.max(target_rom_modes):.6f}")
print(f"Min/Max of Pred ROM modes:   {np.min(predicted_rom_modes):.6f} / {np.max(predicted_rom_modes):.6f}")

mode_rel_error = np.linalg.norm(predicted_rom_modes - target_rom_modes) / (np.linalg.norm(target_rom_modes) + 1e-15)
print(f"\nOverall ROM Modes Relative Error: {mode_rel_error:.4e}")

if num_modes > 1:
    for m in range(num_modes):
        err_m = np.linalg.norm(predicted_rom_modes[:, m] - target_rom_modes[:, m]) / (np.linalg.norm(target_rom_modes[:, m]) + 1e-15)
        print(f"  Mode {m} Relative Error: {err_m:.4e}")

mode_error_num = np.linalg.norm(predicted_rom_modes - target_rom_modes, axis=1)
mode_error_den = np.linalg.norm(target_rom_modes, axis=1) + 1e-15
error_bitmap_modes = np.divide(mode_error_num, mode_error_den) * 100
error_bitmap_modes = error_bitmap_modes.reshape(n_suby, n_subx)

plt.figure(figsize=(7, 6))
plt.imshow(error_bitmap_modes, origin="lower", cmap="magma")
plt.colorbar(label="Relative ROM Mode Error (%)")
plt.title("Error Bitmap (ROM Modes Comparison)")
plt.xlabel("Subdomain x index")
plt.ylabel("Subdomain y index")
plt.tight_layout()
plt.show()
# Reconstruct predicted and target physical solutions
U_pred_full = reconstruct_full_solution(predicted_rom_modes, is_bnd_mask, rom_data, n_subx=n_subx, n_suby=n_suby)
U_true_full = reconstruct_full_solution(target_rom_modes, is_bnd_mask, rom_data, n_subx=n_subx, n_suby=n_suby)

# Calculate global physical field error
rel_error_physical = np.linalg.norm(U_pred_full - U_true_full) / np.linalg.norm(U_true_full)
print(f"Global Reconstructed Physical Solution Relative Error: {rel_error_physical:.4e}")

# Plot ground truth vs. reconstructed physical solution
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

im0 = axes[0].imshow(U_true_full, origin="lower", cmap="viridis")
axes[0].set_title("Ground Truth Physical Solution")
fig.colorbar(im0, ax=axes[0])

im1 = axes[1].imshow(U_pred_full, origin="lower", cmap="viridis")
axes[1].set_title("Reconstructed Prediction")
fig.colorbar(im1, ax=axes[1])

im2 = axes[2].imshow(np.abs(U_pred_full - U_true_full), origin="lower", cmap="magma")
axes[2].set_title("Absolute Error Field")
fig.colorbar(im2, ax=axes[2])

plt.tight_layout()
plt.show()
# Create a copy where only Mode 0 is preserved
predicted_rom_modes_mode0_only = np.zeros_like(predicted_rom_modes)
predicted_rom_modes_mode0_only[:, 0] = predicted_rom_modes[:, 0]

# Reconstruct using only Mode 0
U_pred_mode0 = reconstruct_full_solution(
    predicted_rom_modes_mode0_only, is_bnd_mask, rom_data, n_subx=n_subx, n_suby=n_suby
)

rel_error_mode0 = np.linalg.norm(U_pred_mode0 - U_true_full) / np.linalg.norm(U_true_full)
print(f"Physical Error using ONLY Mode 0: {rel_error_mode0:.4e}")